---
id: rubykaigi2015-lt
base_name: cert-in-gems
tags: []
presentation_date: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: zunda
  email: zundan@gmail.com
  rubygems_user: zundan
  slideshare_user: zunda
  speaker_deck_user: 
